# -*- coding: utf-8 -*-
"""18_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a5ifbCSmzAWUOag2zj0GpjVq946vJ5WE
"""

# !pip install tokenizers
# !pip install datasets
# !pip install transformers
# !pip install sacrebleu
# !pip install deplacy vncorenlp
# !test -d VnCoreNLP || git clone --depth=1 https://github.com/vncorenlp/VnCoreNLP

# Import thu vien
import re
import pandas as pd
# from vncorenlp import VnCoreNLP
import tqdm
import time
# from tokenizers import Tokenizer
# from tokenizers.models import BPE, Unigram, WordLevel, WordPiece
# from tokenizers.trainers import BpeTrainer, WordLevelTrainer, WordPieceTrainer, UnigramTrainer                                
# from tokenizers.pre_tokenizers import Whitespace
# from transformers import PreTrainedTokenizerFast
from tqdm import tqdm
# import datasets
import numpy as np
# from datasets import load_dataset, load_metric
import json
import codecs

# Tao dataframe xu ly na

def load_file(path):
  df= pd.read_csv(path)
  df=df.reset_index(drop=True)
  # df=df.dropna(subset=['en', 'vn'])
  # df=df.astype('string')
  df['text']=df['text'].astype('string')
  print(df.info())
  return df

# Tạo hàm clean dấu hiệu của html

def clean_html(st):
  to_remove_char= ['<v Maximilian>','</aside>','<aside>','<v Jonas>','<v Narrator>', '<v narrator="">', '<v Instructor>', 
                    '</v>','<v -="">', '<v instructor="">', '<v instructor="">','<v Người hướng dẫn>','<pause>',
                    '<v ->', '<br>','<v ->','<thead>','<th>','<the>','<nav>,</nav>','</div>','<div>'
                    ,'<v ->']
  for char in to_remove_char:
      if (st.find(char)==0) or (st.find(char)+len(char))==len(st):
        st=st.replace(char,' ').strip()
  return st


def clean_font(st):
  # st=st.replace('\n',' ')
  st=st.replace('ÂAnd','And')
  st=st.replace('ỵ','ỵ')
  st=st.replace('Ạ','Ạ')
  st=st.replace('ầ','ầ')
  st=st.replace('ồ','ồ')
  st=st.replace('Ồ','Ồ')
  st=st.replace('Ừ','Ừ')
  st=st.replace('è','è')
  st=st.replace('ồ','ồ')
  st=st.replace('ỳ','ỳ')
  st=st.replace('à̀','à')
  st=st.replace('À','À')
  st=st.replace('V̀i','Vì')
  st=st.replace('lam̀','làm')
  st=st.replace('t́','t')
  st=st.replace('à̀','à')
  st=st.replace('r̉','r')
  st=st.replace('ệ','ệ')
  st=st.replace('ế','ế')
  st=st.replace('ề','ề')
  st=st.replace('ể','ể')
  st=st.replace('ể','ể')
  st=st.replace('ế','ế')
  st=st.replace('ế','ế')
  st=st.replace('ể','ể')
  st=st.replace('ẽ','ẽ')
  st=st.replace('ẹ','ẹ')
  st=st.replace('ỡ','ỡ')
  st=st.replace('ờ','ờ')
  st=st.replace('ợ','ợ')
  st=st.replace('​​ờ','ờ')
  st=st.replace('ở','ở')
  st=st.replace('ớ','ớ')
  st=st.replace('ộ','ộ')
  st=st.replace('ộ','ộ')
  st=st.replace('ỗ','ỗ')
  st=st.replace('ố','ố')
  st=st.replace('ó','ó')
  st=st.replace('ọ','ọ')
  st=st.replace('ò','ò')
  st=st.replace('à','à')
  st=st.replace('ả','ả')
  st=st.replace('ạ','ạ')
  st=st.replace('á','á')
  st=st.replace('ã','ã')
  st=st.replace('ā','ã')
  st=st.replace('ẫ','ẫ')
  st=st.replace('ấ','ấ')
  st=st.replace('ẫ','ẫ')
  st=st.replace('ậ','ậ')
  st=st.replace('ắ','ắ')
  st=st.replace('ằ','ằ')
  st=st.replace('ặ','ặ')
  st=st.replace('ụ','ụ')
  st=st.replace('ụ','ụ')
  st=st.replace('ủ','ủ')
  st=st.replace('ú','ú')
  st=st.replace('ù','ù')
  st=st.replace('​ú','ú')
  st=st.replace('ũ','ũ')
  st=st.replace('ử','ử')
  st=st.replace('ừ','ừ')
  st=st.replace('ứ','ứ')
  st=st.replace('ự','ự')
  st=st.replace('ữ','ữ')
  st=st.replace('í','í')
  st=st.replace('ì','ì')
  st=st.replace('ị','ị')
  st=st.replace('u'+'̛','ư')
  st=st.replace('o'+'̛','ơ')
  st=st.replace('a'+'̆' ,'ă')
  char_vi="a ă â e ê o ô ơ i u ư y A Ă Â E Ê O Ô Ơ I U Ư Y".split(' ')
  vi_fix1="ạ ặ ậ ẹ ệ ọ ộ ợ ị ụ ự ỵ Ạ Ặ Ậ Ẹ Ệ Ọ Ộ Ợ Ị Ụ Ự Ỵ".split(' ')
  vi_fix2="á ắ ấ é ế ó ố ớ í ú ứ ý Á Ắ Ấ É Ế Ó Ố Ớ Í Ú Ứ Ý".split(' ')
  vi_fix3="ả ẳ ấ ẻ ể ỏ ổ ở ỉ ủ ử ỷ Ả Ẳ Ẩ Ẻ Ể Ỏ Ổ Ở Ỉ Ủ Ử Ỷ".split(' ')
  vi_fix4="ã ẵ ẫ ẽ ễ õ ỗ ỡ ĩ ũ ữ ỹ Ã Ẵ Ẫ Ẽ Ễ Õ Ỗ Ỡ Ĩ Ũ Ữ Ỹ".split(' ')
  vi_fix5="à ằ ầ è ề ò ồ ờ ì ù ừ ỳ À Ằ Ầ È Ề Ò Ồ Ờ Ì Ù Ừ Ỳ".split(' ')
  for j in range(len(char_vi)):
      st=st.replace(char_vi[j]+'̣',vi_fix1[j])
      st=st.replace(char_vi[j]+'́',vi_fix2[j])
      st=st.replace(char_vi[j]+'̉',vi_fix3[j])
      st=st.replace(char_vi[j]+'̃',vi_fix4[j])
      st=st.replace(char_vi[j]+'̀',vi_fix5[j])
  st=st.replace('\t',' ')
  st=st.replace('Ð','Đ')
  st=st.replace('Ð','Đ')
  st=st.replace('�','')
  st=st.replace('\uf076','')
  st=st.replace('♪','')
  st=st.replace('ГғВўГӮВҖГӮВҷ',"'")
  st=st.replace('т','T')
  st=st.replace('е','e')
  st=st.replace('А','A')
  st=st.replace('а','a')
  st=st.replace('•','')
  st=st.replace('☺','')
  st=st.replace('\u200b','')
  st=st.replace('\u200a','')
  st=st.replace('\xa0','')
  st=st.replace('.','.')
  st=st.replace('…','...')
  st=st.replace('–','-')
  st=st.replace('—','-')
  st=st.replace('”','"')
  st=st.replace('“','"')
  st=st.replace('’',"'")
  st=st.replace(' ',' ')
  st=st.replace('…','...')
  st=st.replace('`',"'")
  st=st.replace('ʻ',"'")
  st=st.replace('|','|')
  st=st.replace('‘',"'")
  st=st.replace('´',"'")
  st=st.replace('́','')
  st=st.replace('̆','')
  st=st.replace('̉','')
  st=st.replace('̃','')
  st=st.replace('̛','')
  st=st.replace('̀','')
  st=st.replace("\'","'")
  st=st.replace('=', ' = ')
  # st=st.replace( '<',' < ')
  # st=st.replace( '>',' > ')
  st=st.replace( '-',' - ')
  st=st.replace( '+',' + ')
  st=st.replace( '*',' * ')
  st=st.replace( '\\',' \\ ')
  st=st.replace( '&',' & ')
  st=st.replace( ':',' : ')
  st=st.replace( '/',' / ')
  st=re.sub(' +', ' ', str(st))
  st=st.replace( " !","!")
  st=st.replace( "$"," $ ")
  st=st.replace( "%"," % ")
  st=st.replace( "+ .","+ .")
  st=st.replace( "\ufeff","")
  # st=st.replace( "'"," ' ")
  st=st.replace("n ' t","n't")
  st=st.replace(" ' re","'re'")
  st=st.replace(" ' ll","'ll")
  st=st.replace('!!','! ')
  st=st.replace('-',' - ')
  st=st.replace('Ã¢ÂÂ', '\'')
  st=st.replace('Ã¢Â\x80Â\x99', '\'')
  st=st.replace('\x1b', ' ')
  st=st.replace('\x08', ' ')
  st=re.sub(' +', ' ', str(st))
  st=st.replace('-',' - ')
  st=st.strip()
  return st


def common_member(a, b):
    a_set = set(a)
    b_set = set(b)
    return list(a_set & b_set)

var=r"""[^A-Z0-9ĐÀÁẠÃẢÂẤẦẨẪẬĂẮẰẶẲẴÔỒỐỔỖỘƠỚỜỠỞỢEÈÉẸẺẼÊẾỀỂỄỆIỊÍÌĨỈỤÚÙŨỦƯỨỪỮỬỰỴÝỲỶỸ]"""  
def gw_match(strg, search=re.compile(var).search):
     return not bool(search(strg))
